# fly.toml app configuration file generated for whatgrowsnativehere on 2026-01-10T16:55:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whatgrowsnativehere'
primary_region = 'iad'

[build]

[deploy]
  strategy="rolling"
  max_unavailable=1

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'false'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024


[[regions]]
  name = "iad" # US East (Washington DC)
  min_machines = 1

[[regions]]
  name = "lax" # US West (Los Angeles)
  min_machines = 1